DEF ESCRIBIR_FICHERO_TEXTO(NOMBRE_FICHERO, TEXTO):
    WITH OPEN(NOMBRE_FICHERO,"W",ENCODING="UTF-8") AS FICHERO:
        FICHERO.WRITE(TEXTO)

DEF LEER_FICHERO_TEXTO(NOMBRE_FICHERO):
    WITH OPEN(NOMBRE_FICHERO, "R", ENCODING="UTF-8") AS FICHERO:
        CONTENIDO = FICHERO.READ()
    RETURN CONTENIDO

DEF COPIAR_FICHERO_TEXTO(FICHERO_ORIGEN, FICHERO_DESTINO):
    CONTENIDO = LEER_FICHERO_TEXTO(FICHERO_ORIGEN)
    ESCRIBIR_FICHERO_TEXTO(FICHERO_DESTINO, CONTENIDO)

#COPIAR UN FICHERO CONVERTIDO EL CONTENIDO A MAÝUSCULAS O A MINÚSCULAS
DEF COPIAR_FICHERO_TEXTO_CONVERTIDO(FICHERO_ORIGEN, FICHERO_DESTINO, TIPO_CONVERSION):
    CONTENIDO_ORIGEN = LEER_FICHERO_TEXTO(FICHERO_ORIGEN)
    IF (TIPO_CONVERSION=="MY"):
        CONTENIDO_FINAL = CONTENIDO_ORIGEN.UPPER()
    ELIF (TIPO_CONVERSION=="MI"):
        CONTENIDO_FINAL = CONTENIDO_ORIGEN.LOWER()
    ELSE:
        CONTENIDO_FINAL = CONTENIDO_ORIGEN
    ESCRIBIR_FICHERO_TEXTO(FICHERO_DESTINO, CONTENIDO_FINAL)

#ESCRIBIR_FICHERO_TEXTO("JUANLUIS.TXT","ESTO ES EL CONTENIDO DEL FICHERO DE JUAN LUIS.\NLEÑA Y CÁSPITAS")
#TODO_EL_CONTENIDO = LEER_FICHERO_TEXTO("JUANLUIS.TXT")
#PRINT(TODO_EL_CONTENIDO)
#COPIAR_FICHERO_TEXTO("JUANLUIS.TXT","COPIA_JL.TXT")

TIPO_CONVERSION = INPUT("INTRODUCE MAYUSCULA O MINUSCULA (MY, MI):")
COPIAR_FICHERO_TEXTO_CONVERTIDO("EJEMPLO_FUNCION_ENCAPSULADA.PY","EJEMPLO_ENUM.PY",TIPO_CONVERSION)

"""SOLUICION DE JUAN LUIS
DEF CONVERSOR_MAYUSCULA_MINUSCULA(LINEA, OPERACION):
    IF (OPERACION=="MY"):
        LINEA_O = LINEA.UPPER()
    ELIF (OPERACION=="MI"):
        LINEA_O = LINEA.LOWER()
    ELSE:
        LINEA_O = LINEA
    RETURN LINEA_O    

DEF COPIAR_FICHERO_TEXTO_CONVERTIDO(FICHERO_ORIGEN, FICHERO_DESTINO, FUNCION):
    ORIGEN = OPEN(FICHERO_ORIGEN, "R")
    DESTINO = OPEN(FICHERO_DESTINO, "W")
    LINEA = ORIGEN.READLINE()
    DESTINO.WRITE(CONVERSOR_MAYUSCULA_MINUSCULA(LINEA, FUNCION))
    WHILE (LINEA!=""):
        LINEA = ORIGEN.READLINE()
        DESTINO.WRITE(CONVERSOR_MAYUSCULA_MINUSCULA(LINEA, FUNCION))
    DESTINO.CLOSE()
    ORIGEN.CLOSE()

CONVERSION = INPUT("INTRODUCE MAYUSCULA O MINUSCULA (MY, MI):")
COPIAR_FICHERO_TEXTO_CONVERTIDO("JUANLUIS.TXT","MODIFICADO.TXT", CONVERSION)
"""