# Generated by Django 4.0.2 on 2022-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
