# Generated by Django 4.0.2 on 2022-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=20)),
            ],
        ),
    ]
