# Generated by Django 4.0.3 on 2022-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
    ]
