# Generated by Django 4.0.3 on 2022-03-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vj_app', '0002_videojuego_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='estado',
        ),
    ]
